# https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#example-configurations

changelog:
  categories:
    - title: 💥 Breaking Changes
      labels:
        - breaking-change
        - msrv
    - title: 🆕 Enhancements
      labels:
        - enhancement
    - title: 🐞 Bugs
      labels:
        - bug
    - title: 🔗 Dependencies
      labels:
        - dependencies
    - title: 🚧 Maintenance
      labels:
        - '*'
      exclude:
        labels:
          - bug
          - breaking-change
          - dependencies
          - enhancement
          - msrv
