name: Bug report
description: Report something that isn't working as expected
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear description of the bug, and what you expected instead.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Minimal reproduction
      description: Code that reproduces the issue, as small as you can make it.
      render: rust
  - type: input
    id: version
    attributes:
      label: s2 version
      placeholder: e.g. 0.1.0
    validations:
      required: true
  - type: input
    id: rust-version
    attributes:
      label: Rust version
      description: Output of `rustc --version`.
    validations:
      required: false
